#!/usr/bin/env sh

set -eu

     BOLD="$(tput bold 2>/dev/null      || printf '')"
     GREY="$(tput setaf 0 2>/dev/null   || printf '')"
UNDERLINE="$(tput smul 2>/dev/null      || printf '')"
      RED="$(tput setaf 1 2>/dev/null   || printf '')"
    GREEN="$(tput setaf 2 2>/dev/null   || printf '')"
   YELLOW="$(tput setaf 3 2>/dev/null   || printf '')"
     BLUE="$(tput setaf 4 2>/dev/null   || printf '')"
  MAGENTA="$(tput setaf 5 2>/dev/null   || printf '')"
 NO_COLOR="$(tput sgr0 2>/dev/null      || printf '')"

_completed()    { printf '%s\n' "${GREEN}✓${NO_COLOR} $*"; }
_info()         { printf '%s\n' "${BOLD}${GREY}>${NO_COLOR} $*"; }
_warn()         { printf '%s\n' "${YELLOW}! $*${NO_COLOR}"; }
_error()        { printf '%s\n' "${RED}x $*${NO_COLOR}" >&2; }
_error_exit()   { _error "$@"; exit 1; }
_exist()        { command -v "$1" 1>/dev/null 2>&1; }

! _exist 'git'  && _error_exit 'install git'
! _exist 'curl' && _error_exit 'install curl'


SUDO=''
if [ "$(id -u)" -ne 0 ]; then
    ! _exist 'sudo' && _error_exit 'sudo is not installed'
    SUDO=$(command -v 'sudo')
    $SUDO -n false 2>/dev/null && _error_exit 'user does not have sudo permissions'
fi

get_distro() {
    [ ! -f "/etc/os-release" ] && _error "/etc/os-release does not exist."
    distro_id=$(grep "^ID=" /etc/os-release | cut -d= -f2 | awk '{print tolower($0)}')
    [ -z "$distro_id" ] && _error 'ID field not found in /etc/os-release.'
    printf '%s' "$distro_id"
}

BASEDIR="$(dirname -- "$( readlink -f -- "$0"; )";)"

distro=$(get_distro)
case "$distro" in 
    "ubuntu") ${BASEDIR}/install-ubuntu.sh "${@}"
    ;;
    "debian") ${BASEDIR}/install-debian.sh "${@}"
    ;;
    "alpine") ${BASEDIR}/install-alpine.sh "${@}"
    ;;
    *)
    _error_exit "${distro} is not a recognized distribution"
esac

exit 0